name: test_env

channels:
  - conda-forge
  - https://heasarc.gsfc.nasa.gov/FTP/software/conda/
  - defaults
  
dependencies:
  - numpy
  - pyyaml>=5.1
  - astropy
  - scipy
  - numdifftools
  - hdf5
  - pytables
  - pandas>=0.23
  - dill
  - wcslib
  - future
  - xspec==12.15.0
  - numba
  - h5py
  - interpolation>=2.2.3
  - libgfortran
  - omegaconf
  - colorama
  - rich
  - joblib
